### ISSUE TITLE
Selecting native messaging core architecture

### ISSUE THREAD

**Issue by cyberphone** [browserext/native-messaging#1]
There are currently two fairly different paths to native messaging:
- Building on the extension scheme originally featured in the _desktop_ version Chrome
- Creating a stand-alone native messaging API

Since there are considerable pros and cons to both approaches, it seems worthwhile taking a concerted decision early on.

On mobile OSes there is currently no native messaging solution available from any vendor.   The protocol handlers in Android and iOS only permit starting native applications which forced Apple to invent an entirely new scheme when they adapted Apple Pay for the Web.

**Comment by aswan** [comment]
Thanks for raising this.

Let me say up front that my first-hand experience developing on mobile platforms is quite limited.  But to start with some background, I think its fair to say that mobile platforms have created a very different model from desktop platforms for the lifecycle of processes, and closely related to that, they have also created new models for inter-process communication (e.g., intents on Android and app extensions on iOS).

From my limited understanding of the IPC APIs on mobile platforms, my instinct is that we would be best served creating separate browser extension APIs (or perhaps even general web APIs) for each of the underlying native APIs.  Library developers will be free to create higher-level cross-platform abstractions for the convenience of extension developers who just want to write something once and have it work everywhere, but extension developers who want to use the features of a specific platform won't run into any constraints that trying to build a single uniform API would inevitably require.

I would like to propose that in the short term, the focus of this project is to agree upon cross-browser standards for native messaging on desktop platforms.  If there is interest in working on standards for mobile platforms, that can proceed as well but frankly I haven't seen much interest in that area from browser vendors.  The important point though is the idea of explicitly separating the design for desktop platforms from the design(s) for mobile platform(s).

Other comments and thoughts are quite welcome.

**Comment by cyberphone** [comment]
The interest from browser vendors introducing Native Messaging to mobile platforms is as you say limited.  

However, the interest from developers for this is huge.  

Anyway, Google, Apple and Samsung are all working with various ways of connecting the Web to their respectively app-based "Wallets".  The idea that there maybe could be a more generic solution has AFAIK never been (publicly) considered.

**Comment by aswan** [comment]
> However, the interest from developers for this is huge.

Can you provide some citations?

> Anyway, Google, Apple and Samsung are all working with various ways of connecting the Web to their respectively app-based "Wallets". The idea that there maybe could be a more generic solution has AFAIK never been (publicly) considered.

I think that without compelling use cases, solving a practical problem that is in front of us rather than some more generalized version of it is simply good engineering practice.  I'm not saying these other use cases don't exist, but I haven't come across them.  If you think they are out there and getting overlooked, please provide some specific references.

**Comment by frivoal** [comment]
**This is a tentative resolution of the CG. See the [minutes of the discussion](http://browserext.github.io/minutes/2016-09-09.html). If no dissenting opinion is expressed here within 10 days, this will be considered the consensus of the CG.**

This seems to address a specialized use case, rather than a generic mechanism, and as such, is out of scope. The appropriate forum is likely to be the [WebPlatform Working Group](https://www.w3.org/WebPlatform/WG/) or the [WICG](https://wicg.io/). The tentative consensus is to reject the proposal.

**Comment by cyberphone** [comment]
@frivoal @aswan @mikepie1 
https://github.com/browserext/native-messaging/issues/2#issuecomment-245822807

**Comment by cyberphone** [comment]
A slight problem with establishing "consensus" at this stage is that neither Microsoft, Google or Apple have expressed any opinion about native messaging.  Well, Microsoft have in a private message to me said that they are working on a native messaging solution but are not ready talking about it right now.

The https://www.w3.org/WebPlatform/WG/ folks are well aware of this topic but have to date shown no interest in it.

Scope change proposal: https://github.com/browserext/browserext.github.io/issues/13

**Comment by cyberphone** [comment]
The more I think of it, I believe that the browser extension CG should update the charter to:

**Comment by frivoal** [comment]
Google is not part of this community group, so their opinion (which has not been expressed one way or the other anyway) is not relevant to the consensus of this community group.

Whether the WebPlatform WG wants to deal with a topic or not does not really change what this group should do.

My take is that: the approach we are trying to develop here was born on the desktop side of things. Independently of which vendor wants to implement what, this approach may turn out to be appropriate for mobile as well, or but at this stage this is not certain. Specific comments about specific manifest keys, or specific APIs, suggesting how changing them would make them better suited for mobile or other platforms is very welcome.

Suggesting that we give up on this approach because it hasn't been implemented on mobile is not helpful. First, maybe it will be. Second, even if it is not, interoperability on desktop is desirable. So this approach will not be abandoned so long as vendors want to pursue it.

Now, if you have a concrete idea of a different approach that would work better for Desktop and Mobile, I highly encourage you to write a (draft) specification for that approach, and to try to convince browser vendors and others that it is a better solution.

Finally, the situation with Payments seems different to me. Developing dedicated APIs to access specific features of operating systems is perfectly legitimate, regardless of the availability of a generic communication mechanism.

**Comment by cyberphone** [comment]
> Finally, the situation with Payments seems different to me. Developing dedicated APIs to access specific features of operating systems is perfectly legitimate, regardless of the availability of a generic communication mechanism.

I'm merely suggesting that a generic communication mechanism would enable

**Comment by frivoal** [comment]
> >  Finally, the situation with Payments seems different to me. Developing dedicated APIs to access specific features of operating systems is perfectly legitimate, regardless of the availability of a generic communication mechanism.
> > I'm merely suggesting that a generic communication mechanism would enable

If you have concrete suggestions of tweaks we could do to the approach we are pursuing to handle that (I mean at the API level, not high level suggestions), such comments are useful and welcome. (I realize that the spec is currently a stub, and that such comments can only be made once there is something to comment on. Hopefully we should have something before long).

If you thing the approach is fundamentally broken **and** you have something concrete to propose instead, presenting a draft specification, and showing how it solves the use cases better would also be useful and welcome.

Stating that a hypothetical but non specified solution would be better may be true, but this is not actionable feedback.

**Comment by cyberphone** [comment]
@frivoal There is a concrete proposal which also is fully testable in Chrome Desktop:
https://github.com/cyberphone/web2native-bridge

I'm not claiming that the current approach is fundamentally broken, only that it doesn't appear to be aligned with mobile OSes.

**Comment by frivoal** [comment]
Follow up in https://github.com/browserext/native-messaging/issues/6
