### ISSUE TITLE
Requirement: Windows data of the calling page

### ISSUE THREAD

**Issue by cyberphone** [browserext/native-messaging#4]
In order to position a native application before it is rendered, it would be nice to get the position of the calling Web page as well as the platform-dependent data needed for making called application "float" on top of the calling page.

**Comment by aswan** [comment]
As with issue #2, this issue is either meant for a different project (direct access from content to native applications) or based on a flawed assumption (browser extension actions always being connected to a specific "calling page")

**Comment by cyberphone** [comment]
Well, the majority of Native Messaging applications are (currently _indirectly_) associated with a specific calling page and this lot could use the mentioned feature.

**Comment by frivoal** [comment]
**This is a tentative resolution of the CG. See the [minutes of the discussion](http://browserext.github.io/minutes/2016-09-09.html). If no dissenting opinion is expressed here within 10 days, this will be considered the consensus of the CG.**

As this is connected to issue #2 which the CG proposes to close as out of scope, this seems also to be out of scope for this Community Group, as it relates to webpages rather than extensions. The appropriate forum is likely to be the [WebPlatform Working Group](https://www.w3.org/WebPlatform/WG/) or the [WICG](https://wicg.io/). In addition, as discussed in https://github.com/browserext/native-messaging/issues/5#issuecomment-245801773, there are already mechanisms to communicate arbitrary information, so specialized ones are not needed. The tentative consensus is to reject the proposal.

**Comment by frivoal** [comment]
Also, see https://github.com/browserext/native-messaging/issues/6
